// LOCALHOST ### Get all customers

GET http://localhost:3002/customers HTTP/1.1

### Get customer by id

GET http://localhost:3002/customers/5ca4bbcea2dd94ee58162a71 HTTP/1.1

### Create customer
POST http://localhost:3002/customers HTTP/1.1 content-type: application/json
  
  {
  "username": "glopez",
  "name": "Jennifer Lawrence",
  "address": "4140 Pamela Hollow Apt. 849, East Elizabeth, TN 29566",
  "birthdate": "1972-11-10T11:01:08.000+00:00",
  "email": "scott50@yahoo.com",
  }

### Delete customer
DELETE http://localhost:3002/customers/ HTTP/1.1